CLASS zcl_s4d400_apt_copy DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_S4D400_APT_COPY IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.

    DATA tt TYPE TABLE OF z01flight.
    SELECT FROM /dmo/flight FIELDS *
        INTO CORRESPONDING FIELDS OF TABLE @tt.
    LOOP AT tt INTO DATA(row).
      INSERT z01flight FROM @row.
    ENDLOOP.

  ENDMETHOD.
ENDCLASS.
